import {
    Zap, Map, HandFist, Bomb, BookUser, Sparkle,
    BrainCircuit, Laugh, MessageCircleHeart, Dessert,
    PocketKnife, GlobeX, Drama, Brain, School, Rocket,
    Sparkles, Flame, Eclipse, Sword, Road, WandSparkles,
    BookOpenText, Castle, ZodiacLibra, BookText, Skull,
    PersonStanding, Users, Wand, CircleQuestionMark,
    ScrollText, Music, Ghost, Siren, Radiation, BrainCog, ClockFading, HeartPlus,
    Rose, CalendarHeart, BookHeart, BowArrow, MessageCircleQuestionMark,
    Venus, Mars, Eye, CircleAlert, Slice, Frown, Syringe,
    CalendarClock, Lasso, Origami, Banana, Scissors,
    type LucideIcon
} from "lucide-react";

const genreIcons: Record<string, LucideIcon> = {
    "Acción": Zap,
    "Aventura": Map,
    "Artes marciales": HandFist,
    "Bélico": Bomb,
    "Biográfico": BookUser,
    "Ciencia ficción": Sparkle,
    "Ciberpunk": BrainCircuit,
    "Comedia": Laugh,
    "Comedia romántica": MessageCircleHeart,
    "Costumbrista": Dessert,
    "Crimen": PocketKnife,
    "Distopía": GlobeX,
    "Drama": Drama,
    "Drama psicológico": Brain,
    "Escolar": School,
    "Espacial": Rocket,
    "Espiritual": Sparkles,
    "Erótico": Flame,
    "Fantasia oscura": Eclipse,
    "Fantasia épica": Sword,
    "Fantasia urbana": Road,
    "Fantasía": WandSparkles,
    "Ficción histórica": BookOpenText,
    "Gótico": Castle,
    "Harem": ZodiacLibra,
    "Histórico": BookText,
    "Horror": Skull,
    "Juvenil": PersonStanding,
    "Lgbtq+": Users,
    "Magia": Wand,
    "Misterio": CircleQuestionMark,
    "Mitológico": ScrollText,
    "Musical": Music,
    "Paranormal": Ghost,
    "Policial": Siren,
    "Postapocalíptico": Radiation,
    "Psicológico": BrainCog,
    "Recuentos de la vida": ClockFading,
    "Reencarnación": HeartPlus,
    "Romance": Rose,
    "Romance contemporáneo": CalendarHeart,
    "Romance histórico": BookHeart,
    "Samurái": BowArrow,
    "Satírico": MessageCircleQuestionMark,
    "Shoujo": Venus,
    "Shounen": Mars,
    "Sobrenatural": Eye,
    "Suspenso": CircleAlert,
    "Thriller": Slice,
    "Tragedia": Frown,
    "Vampiros": Syringe,
    "Vida cotidiana": CalendarClock,
    "Western": Lasso,
    "Xianxia": Origami,
    "Yaoi": Banana,
    "Yuri": Scissors,
}

export const GenreIcon = ({ name, size }: { name: string, size: number }) => {
    const Icon = genreIcons[name];
    return <Icon size={size} />
}
